services:
  papra:
    container_name: papra
    image: corentinth/papra:26.6.1-rootless
    restart: unless-stopped
    ports:
      - "1221:1221"
    environment:
      - APP_BASE_URL=${APP_BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
<<<<<<< HEAD
      - APP_BASE_URL=${APP_BASE_URL}
=======
      - AUTH_FIRST_USER_AS_ADMIN=${AUTH_FIRST_USER_AS_ADMIN}
      - AUTH_IS_EMAIL_VERIFICATION_REQUIRED=${AUTH_IS_EMAIL_VERIFICATION_REQUIRED}
>>>>>>> 3d9131a14671e8cb8e3c2dc4c20b95d09b819065
    volumes:
      - ~/papra/papra-data:/app/app-data
    user: "${UID}:${GID}"
