#!/bin/bash

# Description: Stages updated files to be commited via git. Commits the files and uploads them to the specified remote repo.


echo "Displaying changed files..."
git status

echo "Staging updated files in current directory..."
git add .

echo "Committing files to local repo..."
git commit -m "backup $(date)"

echo "Pushing updated local repo to remote repo..."
git push

echo "Notes successfully uploaded to remote repo."
