#!/bin/bash

# Description: Stages updated files to be commited via git. Commits the files and uploads them to the specified remote repo.

backup() {
  echo "Staging updated files in current directory..."
  git add .

  echo "Committing files to local repo..."
  git commit -m "$(date) $BACKUP_MSG"

  echo "Pushing updated local repo to remote repo..."
  git push

  echo "Notes successfully uploaded to remote repo."
}

BACKUP_MSG="$1"

if [[ -z "$1" ]]; then
  echo "Backup commit message needed"
  exit 1
else
  backup
fi
