#!/bin/bash

# Outputs a fibonacci sequence for a given number.


# Check if argument is given
if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <postive_integer>"
  exit 1
fi

# Check whether the argument is a positive int
if [[ "$1" -le 0 ]]; then
  echo "Error: Please provide a positive integer greater than 0."
  exit 1
fi

count=$1
a=0
b=1
index=0

echo "Fibonacci sequence ($count terms):"

while [[ $index -lt $count ]]; do
  echo -n "$a "
  fn=$(( a + b ))
  a=$b
  b=$fn
  (( index++ ))
done

# Add new line at the end so shell prompt is on a new line.
echo ""
