#!/bin/bash

# Description: Checks whether a file exists. If it doesn't it will return an error (exit code: 1) If it does it will process it.


if [[ ! -f "$1" ]]; then
  echo "File not found: $1"
  exit 1
fi

echo "Processing $1..."
exit 0
