#!/bin/bash

# Description: Validates the length of a password to be larger than 8 characters long.


password=$1

# Validation
if [[ ${#password} -lt 8 ]]; then
	echo "Password too short"
	exit 1
fi
